# Utiliser une image Nginx pour servir les fichiers statiques
FROM nginx:alpine

# Copier les fichiers statiques dans le dossier de Nginx
COPY . /usr/share/nginx/html

# Exposer le port HTTP standard
EXPOSE 80

# Nginx démarrera automatiquement
